RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Category/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Category
{
    public class DetailsModel : PageModel
    {
        public DetailsModel(IAuthenticateService authenticateService, ICategoryService categoryService)
        {
            AuthenticateService = authenticateService;
            CategoryService = categoryService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public ICategoryService CategoryService { get; }

        public Core.Entities.Category Category { get; set; }

        public async Task<IActionResult> OnGet(long ID)
        {
            Category = await GetCategoryByID(ID);

            if (Category.CategoryID == 0)
                return RedirectToPage("/StatusCode", new { code = 400 });

            return Page();
        }

        private async Task<Core.Entities.Category> GetCategoryByID(long ID)
        {
            await RefreshToken();

            var category = await CategoryService.GetByID(Request.Cookies["AccessToken"].ToString(), ID);
            category.VersionNo = Convert.ToBase64String(category.RowVersion);

            return category;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Category/List.cshtml.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Category
{
    public class ListModel : PageModel
    {
        public ListModel(IAuthenticateService authenticateService,
                         ICategoryService categoryService)
        {
            AuthenticateService = authenticateService;
            CategoryService = categoryService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public ICategoryService CategoryService { get; }

        public PaginatedList<RestaurantReservation.Core.Entities.Category> CategoryList { get; set; }

        public string SearchTerm { get; set; }
        public int TotalRow { get; set; }
        public int TotalRowAfterFilter { get; set; }

        private const int PAGE_SIZE = 5;

        [BindProperty(SupportsGet = true)]
        public string DeleteSuccessMessage { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet(string searchString, int? pageIndex)
        {
            await RefreshToken();

            SearchTerm = searchString?.Trim() ?? "";

            var categories = await CategoryService.GetAll(Request.Cookies["AccessToken"].ToString());
            TotalRow = categories.Count();   // Return total number of categories

            if (!string.IsNullOrEmpty(SearchTerm))
                categories = categories.Where(c => c.Name.ToLower().Contains(searchString.ToLower()));

            TotalRowAfterFilter = categories.Count();  // Return total number of categories after filtering
            CategoryList = PaginatedList<RestaurantReservation.Core.Entities.Category>.Create(categories.AsQueryable<RestaurantReservation.Core.Entities.Category>(), pageIndex ?? 1, PAGE_SIZE);

            if (CategoryList.TotalPages < pageIndex && pageIndex > 1)
            {
                pageIndex--;

                return RedirectToPage("List", new { searchString, pageIndex });
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDelete(long id, string searchString, int pageIndex)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            await RefreshToken();
            var success = await CategoryService.Delete(Request.Cookies["AccessToken"].ToString(), id, userId);

            if (!success)
                ErrorMessage = "Category cannot be deleted as there are some restaurants belong to this category.";

            var successMessage = "Category record deleted successfully";
            return RedirectToPage("List", new { searchString, pageIndex, DeleteSuccessMessage = successMessage });

        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Promotions/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Core.ViewModels.Admins;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Promotions
{
    public class DetailsModel : PageModel
    {
        public DetailsModel(IAuthenticateService authenticateService,
                         IPromotionService promotionService)
        {
            AuthenticateService = authenticateService;
            PromotionService = promotionService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public IPromotionService PromotionService { get; }
        [TempData]
        public string ErrorConflictMessage { get; set; }

        public RestaurantPromotionVM RestaurantPromotionVM { get; set; }
        public string Message { get; set; }

        public async Task<IActionResult> OnGet(long PromotionID)
        {
            RestaurantPromotionVM = await GetPromotionByID(PromotionID);

            if (RestaurantPromotionVM == null)
                return RedirectToPage("/StatusCode", new { code = 400 });

            return Page();
        }

        public async Task<IActionResult> OnGetPushEmail(long PromotionID, long RestaurantID)
        {
            await RefreshToken();

            var promotion = await PromotionService.CheckExistingByID(Request.Cookies["AccessToken"].ToString(), PromotionID);
            if (promotion == null)
            {
                ErrorConflictMessage = "The promotion you want to send email has been deleted by another admin";
                return RedirectToPage("/Restaurants/Details", new { ID = RestaurantID });
            }

            var result = await PromotionService.PushEmail(Request.Cookies["AccessToken"].ToString(), PromotionID);

            switch (result)
            {
                case true:
                    Message = $"Email have been sent successfully.";
                    break;
            }

            RestaurantPromotionVM = await GetPromotionByID(PromotionID);
            return Page();
        }

        private async Task<RestaurantPromotionVM> GetPromotionByID(long ID)
        {
            await RefreshToken();

            var result = await PromotionService.GetByID(Request.Cookies["AccessToken"].ToString(), ID);
            result.Promotion.VersionNo = Convert.ToBase64String(result.Promotion.RowVersion);
            result.SelectedType = (int)Enum.Parse(typeof(SD.PromotionType), result.Promotion.Type);

            return result;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Reservation/Details.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IdentityModel;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Core.ViewModels.Admins;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Reservation
{
    public class DetailsModel : PageModel
    {
        public DetailsModel(IAuthenticateService authenticateService,
                            IBookingService bookingService)
        {
            AuthenticateService = authenticateService;
            BookingService = bookingService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public IBookingService BookingService { get; }

        [BindProperty]
        public BookingDetailVM BookingDetailVM { get; set; }
        public string SearchTerm { get; set; }
        public string NotFoundMessage { get; set; }
        public string Message { get; set; }

        [BindProperty(SupportsGet = true)]
        public string BookingNo { get; set; }

        public async Task<IActionResult> OnGetAsync(string searchString)
        {
            string bookingNo = "";
            if (!string.IsNullOrEmpty(BookingNo))
            {
                SearchTerm = BookingNo?.Trim() ?? "";
                bookingNo = BookingNo;
            }
            else
            {
                SearchTerm = searchString?.Trim() ?? "";
                bookingNo = searchString;
            }

            await RefreshToken();
            BookingDetailVM = await BookingService.GetBookingDetailsByNumber(Request.Cookies["AccessToken"].ToString(), bookingNo);

            if (!string.IsNullOrEmpty(searchString) || !string.IsNullOrEmpty(BookingNo))
            {
                if (BookingDetailVM == null)
                    NotFoundMessage = "Invalid Booking Number, please enter another one";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateStatusAsync()
        {
            BookingDetailVM.Booking.BookingStatus = SD.BookingStatus.COMPLETE;
            BookingDetailVM.Booking.CheckIn = DateTime.Now;
            BookingDetailVM.Booking.CheckOut = DateTime.Now;
            BookingDetailVM.Booking.EditedDate = DateTime.Now;
            BookingDetailVM.Booking.EditedBy = User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.GivenName).Value;

            await RefreshToken();
            await BookingService.Update(Request.Cookies["AccessToken"].ToString(), BookingDetailVM.Booking);
            BookingDetailVM = await BookingService.GetBookingDetailsByNumber(Request.Cookies["AccessToken"].ToString(), BookingDetailVM.Booking.BookingNo);

            Message = "Updated Successfully!";
            return Page();
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Reservation/List.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Entities;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Reservation
{
    public class ListModel : PageModel
    {
        public ListModel(IAuthenticateService authenticateService,
                         IBookingService bookingService)
        {
            AuthenticateService = authenticateService;
            BookingService = bookingService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public IBookingService BookingService { get; }

        private const int PAGE_SIZE = 5;
        public PaginatedList<Booking> BookingList { get; set; }

        public string SearchTerm { get; set; }
        public int TotalRow { get; set; }
        public int TotalRowAfterFilter { get; set; }
        public string StatusFilter { get; set; }

        public async Task<IActionResult> OnGet(string searchString, string status, int? pageIndex)
        {
            await RefreshToken();

            StatusFilter = status?.Trim() ?? "All";
            SearchTerm = searchString?.Trim() ?? "";

            var bookings = await BookingService.GetAll(Request.Cookies["AccessToken"].ToString(), StatusFilter);
            TotalRow = bookings.Count();   // Return total number of categories

            if (!string.IsNullOrEmpty(SearchTerm))
                bookings = bookings.Where(b => b.FullName.ToLower().Contains(searchString.ToLower()) ||
                                               b.BookingNo.ToLower().Contains(searchString.Trim().ToLower()));

            TotalRowAfterFilter = bookings.Count();  // Return total number of categories after filtering
            BookingList = PaginatedList<Booking>.Create(bookings.AsQueryable<Booking>(), pageIndex ?? 1, PAGE_SIZE);

            if (BookingList.TotalPages < pageIndex && pageIndex > 1)
            {
                pageIndex--;
                return RedirectToPage("List", new { searchString, status, pageIndex });
            }
            return Page();
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Reservation/Details.cshtml
@page
@using RestaurantReservation.Core.Utils;
@model RestaurantReservation.Frontend.Pages.Admins.Reservation.DetailsModel
@{
    ViewData["Title"] = "Booking Details";
}


<div class="row">
    <div class="col-md-12">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">Booking Details</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                <form method="get" asp-page="/Admins/Reservation/Details">
                    <div class="col-6 input-group mb-3">
                        <input name="searchString" type="text" class="form-control" placeholder="Booking Number" value="@Model.SearchTerm">
                        <div class="input-group-append">
                            @if (!string.IsNullOrEmpty(Model.SearchTerm))
                            {
                                <a asp-page="/Admins/Reservation/Details" class="btn btn-danger">Clear</a>
                            }
                            <input type="submit" value="Search" class="btn btn-info" />
                        </div>
                    </div>
                </form>

                @if (Model.BookingDetailVM != null)
                {
                    <form method="post" asp-page-handler="UpdateStatus">
                        <hr />
                        <h2>Search Result: </h2>
                        <br />
                        <div class="row" style="margin-left:8px">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Booking Number</label>
                                    <p>@Model.BookingDetailVM.Booking.BookingNo</p>
                                </div>

                                <div class="form-group">
                                    <label>Restaurant Name</label>
                                    <p>@Model.BookingDetailVM.BookingDetail.RestaurantSchedule.Restaurant.Name</p>
                                </div>

                                <div class="form-group">
                                    <label>Full Name</label>
                                    <p>@Model.BookingDetailVM.Booking.FullName</p>
                                </div>

                                <div class="form-group">
                                    <label>Phone Number</label>
                                    <p>@Model.BookingDetailVM.Booking.PhoneNo</p>
                                </div>

                                <div class="form-group">
                                    <label>Check In</label>
                                    @if (Model.BookingDetailVM.Booking.CheckIn.HasValue)
                                    {
                                        <p>@Model.BookingDetailVM.Booking.CheckIn?.ToString("dd/MM/yyyy hh:mm tt")</p>
                                    }
                                    else
                                    {
                                        <p> &nbsp;</p>
                                    }
                                </div>

                                <div class="form-group">
                                    <label>Edited By</label>
                                    <p>@Model.BookingDetailVM.Booking.EditedBy</p>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Booking Date</label>
                                    <p>@Model.BookingDetailVM.Booking.BookingDate</p>
                                </div>

                                <div class="form-group">
                                    <label>Booking Session</label>
                                    <p>@Model.BookingDetailVM.BookingDetail.RestaurantSchedule.ScheduleDate.ToString("dd/MM/yyyy") @Model.BookingDetailVM.BookingDetail.RestaurantSchedule.StartTime.ToString("hh:mm tt") - @Model.BookingDetailVM.BookingDetail.RestaurantSchedule.EndTime.ToString("hh:mm tt")</p>
                                </div>

                                <div class="form-group">
                                    <label>Number of Pax</label>
                                    <p>@Model.BookingDetailVM.BookingDetail.Pax</p>
                                </div>

                                <div class="form-group">
                                    <label>Status</label>
                                    @{
                                        string bookingStatus = Model.BookingDetailVM.Booking.BookingStatus;
                                        switch (bookingStatus)
                                        {
                                            case SD.BookingStatus.COMPLETE:
                                                <p><span class="badge badge-success">Complete</span></p>
                                                break;
                                            case SD.BookingStatus.PENDING:
                                                <p><span class="badge badge-primary">Pending</span></p>
                                                break;
                                            case SD.BookingStatus.EXPIRED:
                                                <p><span class="badge badge-danger">Expired</span></p>
                                                break;
                                        }
                                    }
                                </div>

                                <div class="form-group">
                                    <label>Check Out</label>
                                    @if (Model.BookingDetailVM.Booking.CheckOut.HasValue)
                                    {
                                        <p>@Model.BookingDetailVM.Booking.CheckOut?.ToString("dd/MM/yyyy hh:mm tt")</p>
                                    }
                                    else
                                    {
                                        <p> &nbsp;</p>
                                    }
                                </div>

                                <div class="form-group">
                                    <label>Edited Date</label>
                                    @if (Model.BookingDetailVM.Booking.EditedDate != default(DateTime))
                                    {
                                        <p>@Model.BookingDetailVM.Booking.EditedDate.ToString("dd/MM/yyyy hh:mm tt")</p>
                                    }
                                </div>

                            </div>
                        </div>

                        <br />

                        @{
                            if (bookingStatus.Equals(SD.BookingStatus.PENDING))
                            {
                                <input type="hidden" asp-for="BookingDetailVM.Booking.BookingID" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.UserID" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.ApplicationUser" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.BookingDate" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.BookingNo" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.FullName" />
                                <input type="hidden" asp-for="BookingDetailVM.Booking.PhoneNo" />

                                <button onclick="showConfirmationDialog('complete')" class="btn btn-success form-control mb-2">
                                    Complete
                                </button>
                            }
                        }
                        <br />
                    </form>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <script>
            $(document).ready(function() {
                var Toast = Swal.mixin({
                    toast: true,
                    position: "top-end",
                    showConfirmButton: false,
                    timer: 7000
                });

                Toast.fire({
                    icon: "success",
                    title: "@Model.Message",
                })
            });
        </script>
    }

    @if (!string.IsNullOrEmpty(Model.NotFoundMessage))
    {
        <script>
            $(document).ready(function() {
                var Toast = Swal.mixin({
                    toast: true,
                    position: "top-end",
                    showConfirmButton: false,
                    timer: 7000
                });

                Toast.fire({
                    icon: "error",
                    title: "@Model.NotFoundMessage",
                })
            });
        </script>
    }
}

@section PageHeader {
    <div class="col-sm-6">
        <h1 class="m-0">Booking Details</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-page="/Admins/Home">Home</a></li>
            <li class="breadcrumb-item active">Booking Details</li>
        </ol>
    </div>
}