RestaurantReservation.Frontend/RestaurantReservation.Frontend/ViewComponents/ReservationCountSideViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantReservation.Frontend.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantReservation.Frontend.ViewComponents
{
    public class ReservationCountSideViewComponent : ViewComponent
    {
        private readonly IBookingService bookingService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public ReservationCountSideViewComponent(IBookingService bookingService,
                                             IHttpContextAccessor httpContextAccessor)
        {
            this.bookingService = bookingService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await bookingService.AdminGetPendingCount());
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/ViewComponents/ReservationCountViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantReservation.Frontend.Services.Interfaces;
using System.Threading.Tasks;

namespace RestaurantReservation.Frontend.ViewComponents
{
    public class ReservationCountViewComponent : ViewComponent
    {
        private readonly IBookingService bookingService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public ReservationCountViewComponent(IBookingService bookingService,
                                             IHttpContextAccessor httpContextAccessor)
        {
            this.bookingService = bookingService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await bookingService.AdminGetPendingCount());
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Shared/_Layout.cshtml
@using RestaurantReservation.Core.Utils;
@using IdentityModel;
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - T-Cube</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/theme/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/theme/dist/css/adminlte.min.css">
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/theme/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">

    @RenderSection("CSS", required: false)
</head>
<body class="hold-transition sidebar-mini layout-footer-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole(SD.ROLE_ADMIN))
                    {
                        <li class="nav-item">
                            <a asp-page="/Admins/Home" class="nav-link">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a asp-page="/Admins/Reservation/List" asp-route-status="@SD.BookingStatus.PENDING" class="nav-link">
                                Reservations
                                @await Component.InvokeAsync("ReservationCount")
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-page="/Admins/Category/List" class="nav-link">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a asp-page="/Admins/Restaurants/List" class="nav-link">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a asp-page="/Admins/Users/List" class="nav-link">Users</a>
                        </li>
                    }
                    else if (User.IsInRole(SD.ROLE_MEMBER))
                    {
                        <li class="nav-item">
                            <a asp-page="/Index" class="nav-link">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a asp-page="/Members/History/List" class="nav-link">History</a>
                        </li>
                        @*
                            <li class="nav-item">
                                <a asp-page="/Members/Reservation/List" class="nav-link">Reservation</a>
                            </li>
                        *@
                    }
                }
                else
                {
                    <li class="nav-item">
                        <a asp-page="/Account/Login" class="nav-link">Login</a>
                    </li>
                }
            </ul>

            @if (User.Identity.IsAuthenticated)
            {
                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-page="/Account/Logout">
                            <i class="fas fa-door-open"></i>
                        </a>
                    </li>
                </ul>
            }
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-page="/Index" class="brand-link">
                <img src="~/favicon.ico" alt="T-Cube Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">T-Cube</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                @if (User.Identity.IsAuthenticated)
                {
                    string name = httpContextAccessor.HttpContext.User.FindFirst(JwtClaimTypes.GivenName).Value;

                    <!-- Sidebar user (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="~/theme/dist/img/avatar.jpg" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a class="d-block" asp-page="/Account/Profile">@name</a>
                        </div>
                    </div>
                }
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole(SD.ROLE_ADMIN))
                            {
                                <li class="nav-item">
                                    <a asp-page="/Admins/Reservation/List" asp-route-status="@SD.BookingStatus.PENDING" class="nav-link">
                                        <i class="nav-icon far fa-calendar-alt"></i>
                                        <p>
                                            Reservation
                                            @await Component.InvokeAsync("ReservationCountSide")
                                        </p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a asp-page="/Admins/Category/List" class="nav-link">
                                        <i class="nav-icon far fa-list-alt"></i>
                                        <p>
                                            Categories
                                        </p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a asp-page="/Admins/Restaurants/List" class="nav-link">
                                        <i class="nav-icon fa fa-home"></i>
                                        <p>
                                            Restaurants
                                        </p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a asp-page="/Admins/Users/List" class="nav-link">
                                        <i class="nav-icon fa fa-users"></i>
                                        <p>
                                            Users
                                        </p>
                                    </a>
                                </li>
                            }
                            else if (User.IsInRole(SD.ROLE_MEMBER))
                            {
                                <li class="nav-item">
                                    <a asp-page="/Index" class="nav-link">
                                        <i class="nav-icon fa fa-heart"></i>
                                        <p>
                                            Restaurants
                                        </p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-page="/Members/History/List" class="nav-link">
                                        <i class="nav-icon fa fa-history"></i>
                                        <p>
                                            History
                                        </p>
                                    </a>
                                </li>
                                @*
                                    <li class="nav-item">
                                        <a asp-page="/Members/Reservation/List" class="nav-link">
                                            <i class="nav-icon far fa-calendar-alt"></i>
                                            <p>
                                                Reservation
                                            </p>
                                        </a>
                                    </li>
                                *@
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-page="/Account/Login" class="nav-link">
                                    <i class="nav-icon fas fa-sign-in-alt"></i>
                                    <p>
                                        Login
                                    </p>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        @RenderSection("PageHeader", required: false)
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="#">T-Cube</a></strong>

            <div class="float-right d-none d-sm-block">
                All rights reserved.
            </div>
        </footer>

        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
    </div>
    <!-- jQuery -->
    <script src="~/theme/plugins/jquery/jquery.min.js"></script>

    <!-- jQuery Validation -->
    <script src="~/theme/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/theme/plugins/jquery-validation/jquery.validate.unobtrusive.min.js"></script>

    <!-- Bootstrap 4 -->
    <script src="~/theme/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/theme/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/theme/dist/js/demo.js"></script>

    <!-- SweetAlert2 -->
    <script src="~/theme/plugins/sweetalert2/sweetalert2.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>