RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Category/Create.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IdentityModel;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Category
{
    public class CreateModel : PageModel
    {
        public CreateModel(IAuthenticateService authenticateService,
                           ICategoryService categoryService)
        {
            AuthenticateService = authenticateService;
            CategoryService = categoryService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public ICategoryService CategoryService { get; }

        [BindProperty]
        public Core.Entities.Category Category { get; set; }

        [TempData]
        public string Message { get; set; }

        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await RefreshToken();

            Category.CreatedBy = User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.GivenName).Value;
            Category.CreatedDate = DateTime.Now;
            var success = await CategoryService.Add(Request.Cookies["AccessToken"].ToString(), Category);
            if (success)
            {
                Message = $"New category {Category.Name} added successfully.";
                return RedirectToPage("List");
            }
            else
            {
                ErrorMessage = $"{Category.Name} Category cannot be added due to duplicate name, try another one.";
                return Page();
            }
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Category/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Category
{
    public class DetailsModel : PageModel
    {
        public DetailsModel(IAuthenticateService authenticateService, ICategoryService categoryService)
        {
            AuthenticateService = authenticateService;
            CategoryService = categoryService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public ICategoryService CategoryService { get; }

        public Core.Entities.Category Category { get; set; }

        public async Task<IActionResult> OnGet(long ID)
        {
            Category = await GetCategoryByID(ID);

            if (Category.CategoryID == 0)
                return RedirectToPage("/StatusCode", new { code = 400 });

            return Page();
        }

        private async Task<Core.Entities.Category> GetCategoryByID(long ID)
        {
            await RefreshToken();

            var category = await CategoryService.GetByID(Request.Cookies["AccessToken"].ToString(), ID);
            category.VersionNo = Convert.ToBase64String(category.RowVersion);

            return category;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Category/Edit.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IdentityModel;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Category
{
    public class EditModel : PageModel
    {
        public EditModel(IAuthenticateService authenticateService,
                           ICategoryService categoryService)
        {
            AuthenticateService = authenticateService;
            CategoryService = categoryService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public ICategoryService CategoryService { get; }

        [BindProperty]
        public Core.Entities.Category Category { get; set; }

        [TempData]
        public string Message { get; set; }
        [TempData]
        public string ConflictErrorMessage { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet(long ID)
        {
            Category = await GetCategoryByID(ID);

            if (Category.CategoryID == 0)
                return RedirectToPage("/StatusCode", new { code = 400 });

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await RefreshToken();

                Category.EditedBy = User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.GivenName).Value;
                Category.EditedDate = DateTime.Now;

                var result = await CategoryService.Update(Request.Cookies["AccessToken"].ToString(), Category);
                switch (result)
                {
                    case SD.StatusCode.OK:
                        Message = $"Category {Category.Name} existing info updated successfully.";
                        return RedirectToPage("List");
                    case SD.StatusCode.BAD_REQUEST:
                        ErrorMessage = "Duplicate category name is prohibited, try another one";
                        break;
                    case SD.StatusCode.INTERNAL:
                        return RedirectToPage("/Error");
                    default:
                        ConflictErrorMessage = "The record you attempted to edit was modified by another user after you got the original value. The edit operation was cancelled. If you still want to edit this record, edit again.";
                        return RedirectToPage("List");
                }
            }
            return Page();
        }

        private async Task<Core.Entities.Category> GetCategoryByID(long ID)
        {
            await RefreshToken();

            var category = await CategoryService.GetByID(Request.Cookies["AccessToken"].ToString(), ID);
            category.VersionNo = Convert.ToBase64String(category.RowVersion);

            return category;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Promotions/Create.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IdentityModel;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Entities;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Core.ViewModels.Admins;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Promotions
{
    public class CreateModel : PageModel
    {
        public CreateModel(IAuthenticateService authenticateService,
                           IRestaurantService restaurantService,
                           IPromotionService promotionService)
        {
            AuthenticateService = authenticateService;
            RestaurantService = restaurantService;
            PromotionService = promotionService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public IRestaurantService RestaurantService { get; }
        [Inject]
        public IPromotionService PromotionService { get; }

        [BindProperty]
        public RestaurantPromotionVM RestaurantPromotionVM { get; set; }

        [TempData]
        public string Message { get; set; }

        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet(long RestaurantID)
        {
            await RefreshToken();

            var restaurant = await GetRestaurantDetails(RestaurantID);

            RestaurantPromotionVM = new RestaurantPromotionVM
            {
                RestaurantID = restaurant.RestaurantID,
                RestaurantName = restaurant.Name,
                RestaurantWorkingDay = restaurant.WorkingDay,
                StartWorkingTime = restaurant.StartWorkingTime,
                EndWorkingTime = restaurant.EndWorkingTime,
                Promotion = new Promotion(),
            };
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                RestaurantPromotionVM.Promotion.CreatedBy = User.Claims.FirstOrDefault(x => x.Type == JwtClaimTypes.GivenName).Value;
                RestaurantPromotionVM.Promotion.CreatedDate = DateTime.Now;
                RestaurantPromotionVM.Promotion.isAvailable = true;
                RestaurantPromotionVM.Promotion.Type = Enum.GetName(typeof(SD.PromotionType), Convert.ToInt32(RestaurantPromotionVM.Promotion.Type));
                RestaurantPromotionVM.Promotion.RestaurantID = RestaurantPromotionVM.RestaurantID;
                RestaurantPromotionVM.Promotion.isEmailCreatedSent = false;

                await RefreshToken();
                var result = await PromotionService.Add(Request.Cookies["AccessToken"].ToString(), RestaurantPromotionVM.Promotion);

                if (result)
                {
                    Message = $"New promotion added successfully.";
                    return RedirectToPage("/Restaurants/Details", new { ID = RestaurantPromotionVM.RestaurantID });
                }
                else
                {
                    ModelState.AddModelError("RestaurantPromotionVM.Promotion.Name", "Duplicate Promotion Name Detected");
                    ErrorMessage = "Failed to add promotion, please try another info";
                }
            }
            return Page();
        }

        private async Task<Restaurant> GetRestaurantDetails(long ID)
        {
            await RefreshToken();
            var restaurantDetails = await RestaurantService.GetByID(Request.Cookies["AccessToken"].ToString(), ID, "All", "All");
            return restaurantDetails.Restaurant;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Promotions/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantReservation.Core.Utils;
using RestaurantReservation.Core.ViewModels.Admins;
using RestaurantReservation.Frontend.Services.Interfaces;

namespace RestaurantReservation.Frontend.Pages.Admins.Promotions
{
    public class DetailsModel : PageModel
    {
        public DetailsModel(IAuthenticateService authenticateService,
                         IPromotionService promotionService)
        {
            AuthenticateService = authenticateService;
            PromotionService = promotionService;
        }

        [Inject]
        public IAuthenticateService AuthenticateService { get; }
        [Inject]
        public IPromotionService PromotionService { get; }
        [TempData]
        public string ErrorConflictMessage { get; set; }

        public RestaurantPromotionVM RestaurantPromotionVM { get; set; }
        public string Message { get; set; }

        public async Task<IActionResult> OnGet(long PromotionID)
        {
            RestaurantPromotionVM = await GetPromotionByID(PromotionID);

            if (RestaurantPromotionVM == null)
                return RedirectToPage("/StatusCode", new { code = 400 });

            return Page();
        }

        public async Task<IActionResult> OnGetPushEmail(long PromotionID, long RestaurantID)
        {
            await RefreshToken();

            var promotion = await PromotionService.CheckExistingByID(Request.Cookies["AccessToken"].ToString(), PromotionID);
            if (promotion == null)
            {
                ErrorConflictMessage = "The promotion you want to send email has been deleted by another admin";
                return RedirectToPage("/Restaurants/Details", new { ID = RestaurantID });
            }

            var result = await PromotionService.PushEmail(Request.Cookies["AccessToken"].ToString(), PromotionID);

            switch (result)
            {
                case true:
                    Message = $"Email have been sent successfully.";
                    break;
            }

            RestaurantPromotionVM = await GetPromotionByID(PromotionID);
            return Page();
        }

        private async Task<RestaurantPromotionVM> GetPromotionByID(long ID)
        {
            await RefreshToken();

            var result = await PromotionService.GetByID(Request.Cookies["AccessToken"].ToString(), ID);
            result.Promotion.VersionNo = Convert.ToBase64String(result.Promotion.RowVersion);
            result.SelectedType = (int)Enum.Parse(typeof(SD.PromotionType), result.Promotion.Type);

            return result;
        }

        private async Task RefreshToken()
        {
            var userToken = await AuthenticateService.RefreshToken(Request.Cookies["AccessToken"].ToString(), Request.Cookies["RefreshToken"].ToString());
            HttpContext.Response.Cookies.Delete("AccessToken");
            HttpContext.Response.Cookies.Append("AccessToken",
                                                userToken.Token,
                                                new CookieOptions
                                                {
                                                    HttpOnly = true,
                                                    SameSite = SameSiteMode.Strict
                                                });
        }
    }
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Promotions/Create.cshtml
@page  "{RestaurantID:long}"
@using RestaurantReservation.Core.Utils;
@model RestaurantReservation.Frontend.Pages.Admins.Promotions.CreateModel
@{
    ViewData["Title"] = "Create Restaurant Promotions";
}


<form method="post">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Promotion Details</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>

                <div class="card-body">
                    <input hidden="hidden" asp-for="@Model.RestaurantPromotionVM.RestaurantID" />

                    <h3 class="my-3">@Model.RestaurantPromotionVM.RestaurantName</h3>

                    <hr>
                    <h4>Operating Hour</h4>
                    <p><span id="workingDay">@Model.RestaurantPromotionVM.RestaurantWorkingDay</span> @Model.RestaurantPromotionVM.StartWorkingTime.ToString("hh:mm tt") - @Model.RestaurantPromotionVM.EndWorkingTime.ToString("hh:mm tt")</p>

                    <br />

                    <div class="form-group">
                        <label asp-for="RestaurantPromotionVM.Promotion.Name">Name</label> <span class="text-danger"><b>*</b></span>
                        <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Name" required />
                        <span asp-validation-for="RestaurantPromotionVM.Promotion.Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="RestaurantPromotionVM.Promotion.Description">Description</label> <span class="text-danger"><b>*</b></span>
                        <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Description" required />
                        <span asp-validation-for="RestaurantPromotionVM.Promotion.Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="RestaurantPromotionVM.Promotion.Content">Content</label> <span class="text-danger"><b>*</b></span>
                        <textarea id="inputDescription" class="form-control" rows="3" asp-for="RestaurantPromotionVM.Promotion.Content"></textarea>
                        <span asp-validation-for="RestaurantPromotionVM.Promotion.Content" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="RestaurantPromotionVM.Promotion.Type">Type</label> <span class="text-danger"><b>*</b></span>
                        <select id="typeDropDown" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Type" asp-items="Html.GetEnumSelectList<SD.PromotionType>()" required>
                            <option disabled>Please choose one of them</option>
                        </select>
                        <span asp-validation-for="RestaurantPromotionVM.Promotion.Type" class="text-danger"></span>
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="RestaurantPromotionVM.Promotion.StartDate">Start Date</label> <span class="text-danger"><b>*</b></span>
                                <input type="date" class="form-control" id="startDate" asp-for="RestaurantPromotionVM.Promotion.StartDate" value="@DateTime.Now.ToString("dd/MM/yyyy")" required />
                                <span asp-validation-for="RestaurantPromotionVM.Promotion.StartDate" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="RestaurantPromotionVM.Promotion.EndDate">End Date</label> <span class="text-danger"><b>*</b></span>
                                <input type="date" class="form-control" id="endDate" asp-for="RestaurantPromotionVM.Promotion.EndDate" value="@DateTime.Now.ToString("dd/MM/yyyy")" required />
                                <span asp-validation-for="RestaurantPromotionVM.Promotion.EndDate" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <br />
                    <div asp-validation-summary="All" class="text-danger"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary" asp-page="/Restaurants/Details" asp-route-ID="@Model.RestaurantPromotionVM.RestaurantID">Cancel</a>
            <input type="submit" value="Create" class="btn btn-primary float-right" asp-page-handler="Submit" />
        </div>
    </div>
</form>
<br />
<br />

@section Scripts {
    <script type="text/javascript">
        $(function () {
            var dtToday = new Date();

            var month = dtToday.getMonth() + 1;
            var day = dtToday.getDate();
            var year = dtToday.getFullYear();
            if (month < 10)
                month = '0' + month.toString();
            if (day < 10)
                day = '0' + day.toString();

            var maxDate = year + '-' + month + '-' + day;

            // or instead:
            // var maxDate = dtToday.toISOString().substr(0, 10);
            $('#startDate').attr('min', maxDate);
            $('#endDate').attr('min', maxDate);
        });
    </script>
}


@section PageHeader {
    <div class="col-sm-6">
        <h1 class="m-0">New Restaurant Promotions</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-page="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-page="/Admins/Restaurants/List">Restaurants</a></li>
            <li class="breadcrumb-item"><a asp-page="/Restaurants/Details" asp-route-ID="@Model.RestaurantPromotionVM.RestaurantID">Details</a></li>
            <li class="breadcrumb-item active">Create Promotion</li>
        </ol>
    </div>
}

RestaurantReservation.Frontend/RestaurantReservation.Frontend/Pages/Admins/Promotions/Details.cshtml
@page "{PromotionID:int}"
@model RestaurantReservation.Frontend.Pages.Admins.Promotions.DetailsModel
@{
    ViewData["Title"] = "Promotion Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">Promotion Details</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.PromotionID" />
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.CreatedBy" />
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.CreatedDate" />
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.isAvailable" />
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.RestaurantID" />
                <input hidden="hidden" asp-for="RestaurantPromotionVM.Promotion.VersionNo" />

                <h3 class="my-3">@Model.RestaurantPromotionVM.RestaurantName</h3>

                <hr>
                <h4>Operating Hour</h4>
                <p><span id="workingDay">@Model.RestaurantPromotionVM.RestaurantWorkingDay</span> @Model.RestaurantPromotionVM.StartWorkingTime.ToString("hh:mm tt") - @Model.RestaurantPromotionVM.EndWorkingTime.ToString("hh:mm tt")</p>

                <br />

                <div class="form-group">
                    <label asp-for="RestaurantPromotionVM.Promotion.Name">Promotion Name</label>
                    <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Name" disabled />
                </div>

                <div class="form-group">
                    <label asp-for="RestaurantPromotionVM.Promotion.Description">Description</label>
                    <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Description" disabled />
                </div>

                <div class="form-group">
                    <label asp-for="RestaurantPromotionVM.Promotion.Content">Content</label>
                    <textarea id="inputDescription" class="form-control" rows="3" asp-for="RestaurantPromotionVM.Promotion.Content" disabled></textarea>
                </div>

                <div class="form-group">
                    <label asp-for="RestaurantPromotionVM.Promotion.Type">Type</label>
                    <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.Type" disabled />
                </div>

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.StartDate">Start Date</label>
                            <input type="text" class="form-control" value="@Model.RestaurantPromotionVM.Promotion.StartDate.ToString("dd/MM/yyyy")" disabled />
                        </div>

                        <br /><br />

                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.CreatedBy">Created By</label>
                            <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.CreatedBy" disabled />
                        </div>

                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.EditedBy">Edited By</label>
                            <input type="text" class="form-control" asp-for="RestaurantPromotionVM.Promotion.EditedBy" disabled />
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.EndDate">End Date</label>
                            <input type="text" class="form-control" value="@Model.RestaurantPromotionVM.Promotion.EndDate.ToString("dd/MM/yyyy")" disabled />
                        </div>

                        <br /><br />

                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.CreatedDate">Created Date</label>
                            <input type="text" class="form-control" value="@Model.RestaurantPromotionVM.Promotion.CreatedDate.ToString("dd/MM/yyyy")" disabled />
                        </div>

                        <div class="form-group">
                            <label asp-for="RestaurantPromotionVM.Promotion.EditedDate">Edited Date</label>
                            <input type="text" class="form-control" value="@Model.RestaurantPromotionVM.Promotion.EditedDate?.ToString("dd/MM/yyyy")" disabled />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <a class="btn btn-secondary" asp-page="/Restaurants/Details" asp-route-ID="@Model.RestaurantPromotionVM.RestaurantID">Back</a>
        @if (!Model.RestaurantPromotionVM.Promotion.isEmailCreatedSent)
        {
            <a class="btn btn-primary float-right" asp-page="/Admins/Promotions/Details" asp-page-handler="PushEmail" asp-route-PromotionID="@Model.RestaurantPromotionVM.Promotion.PromotionID" asp-route-RestaurantID="@Model.RestaurantPromotionVM.Promotion.RestaurantID">
                Push Email
            </a>
        }
    </div>
</div>
<br />
<br />

@section Scripts {
    @if (!String.IsNullOrEmpty(Model.Message))
    {
        <script>
            $(document).ready(function() {
                var Toast = Swal.mixin({
                    toast: true,
                    position: "top-end",
                    showConfirmButton: false,
                    timer: 7000
                });
                Toast.fire({
                    icon: "success",
                    title: "@Model.Message",
                })
            });
        </script>
    }
}

@section PageHeader {
    <div class="col-sm-6">
        <h1 class="m-0">Existing Announcement & Promotion</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-page="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-page="/Admins/Restaurants/List">Restaurants</a></li>
            <li class="breadcrumb-item"><a asp-page="/Restaurants/Details" asp-route-ID="@Model.RestaurantPromotionVM.RestaurantID">Details</a></li>
            <li class="breadcrumb-item active">Promotion Details</li>
        </ol>
    </div>
}